export const FETCH_DOCUMENTS = "FETCH_DOCUMENTS";
export const CREATE_DOCUMENT = "CREATE_DOCUMENT";
export const DELETE_DOCUMENT = "DELETE_DOCUMENT";

export const STORE_DOCUMENT = "STORE_DOCUMENT";
export const RETRIEVE_DOCUMENT = "RETRIEVE_DOCUMENT";

export const FETCH_DOCUMENT_HISTORY = "FETCH_DOCUMENT_HISTORY";

export const SELECT_DOCUMENT = "SELECT_DOCUMENT";
